export const GET_HEADER_DETAILS_REQUEST = "GET_PRODUCT_DEFINITION_REQUEST";
export const GET_HEADER_DETAILS_SUCCESS = 'GET_HEADER_DETAILS_SUCCESS';
export const GET_HEADER_DETAILS_ERROR = 'GET_HEADER_DETAILS_ERROR';